OnyJ/kitten_e_commerce

- app/models/item.rb
- db/migrate/20200309133128_create_items.rb
- test/fixtures/items.yml
- test/models/item_test.rb
Hello,
Items table has been created.
> Items table

- README.md
- app/models/item.rb
- db/migrate/20200309133128_create_items.rb
- db/schema.rb
- test/fixtures/items.yml
- test/models/item_test.rb
> Items table migration

- app/views/layouts/application.html.erb
Framework JS Boostrap CDN in app/views/layouts/application.html.erb
And Framework CSS Bootswatch in same file.
> Framework JS Bootstrap

- app/views/layouts/application.html.erb
Framework CSS CDN in app/views/layout/application.html.erb
> framework CSS CDN

- db/seeds.rb
> fix seeds.rb

- app/assets/javascripts/items.coffee
- app/assets/stylesheets/items.scss
- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
- app/models/item.rb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- test/controllers/items_controller_test.rb
> Crud items

- config/environments/production.rb
Edit production.rb to have mailer working from production (with devise).
> devise - edit production.rb for mailer

- app/views/items/_card.html.erb
- app/views/items/index.html.erb
- db/seeds.rb
View de l'index "terminée", cards générées et lien mort dans le seed supprimé
> view Index + _card, changement sur seed

- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
Footer partial and render in app/views/layouts/application.html.erb
> footer partial and render in application.html.erb

- db/seeds.rb
Removed broken cat image link.
> fix seed - cat images

- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
Navbar
Missing : cart route (show) for "Mon panier" and user route (show) for "Mon compte"
> header navbar, cart routes missing

- app/views/items/_card.html.erb
> changements de l'affichage des cartes

- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
J'ai centré le "Vous avez oublié votre mot de passe" pour un formulaire plus stylay
> center forgotten password?

- app/models/cart.rb
- app/models/item.rb
- app/models/line_item.rb
- app/models/user.rb
- db/migrate/20200310124058_create_carts.rb
- db/migrate/20200310130024_create_line_items.rb
- db/schema.rb
- test/fixtures/carts.yml
- test/fixtures/line_items.yml
- test/models/cart_test.rb
- test/models/line_item_test.rb
> Create cart table

- app/views/items/_card.html.erb
- app/views/items/show.html.erb
faut juste rajouter les paths quand ils seront faits
> Edit "_card" + show products(à terminer)

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/user_mailer/welcome_email.html.erb
- app/views/user_mailer/welcome_email.text.erb
- config/environment.rb
- config/environments/development.rb
- test/mailers/previews/user_mailer_preview.rb
- test/mailers/user_mailer_test.rb
A welcome email is opened automatically in the browser when a sign up is done on the current computer.
1. Sign up
2. Welcome email is opened in the browser.
> Create action mailer

- app/views/items/_card.html.erb
- app/views/items/index.html.erb
Size image
Buttons cards aligment
Space between cards
> buttons cards alignement fixed and card presentation

- app/views/items/_card.html.erb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
New presentation with smaller image on the left and item information on the right.
> Item show page front corrections

- .gitignore
- Gemfile
- Gemfile.lock
- config/environment.rb
Add mailer to production environment.
> Mailer production

- app/views/items/_card.html.erb
- app/views/items/index.html.erb
- app/views/layouts/_header.html.erb
> small corrections

- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/_sign_up_form.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/sessions/_log_in_form.html.erb
Responsive forms for :
- new password
- edit password
- sign up
- sign in
- edit profile
> responsive form pw(2) sign_up sign_in and edit

- app/controllers/carts_controller.rb
- app/views/carts/destroy.js.erb
- app/views/carts/show.html.erb
Correction du bug dans le controller cart, qui supprimait les items en db au lieu de seulement les supprimer du panier.
> ajax front show cart + bug fixed line_item.destroy

- app/assets/stylesheets/application.css
- app/assets/stylesheets/cards.css
> cards effects on hover
